from Chess import Board
import chess
b =Board()
b.push_san("e4")
matrix = b.board_to_input()
print(matrix)
print(len(matrix))
b.push_san("e5")
b.push_san("Nf3")
b.push_san("Nc6")
b.push_san("Bb5")
b.push_san("a6")
matrix = b.board_to_input()
print(len(matrix))
print(len(matrix[-1]))
b.push_san("Ba4")
b.push_san("Nf6")
b.push_san("O-O")
print(b.board)